### ISSUE TITLE
Refactor check_articles() to return a string instead of printing to terminal

### ISSUE THREAD

**Issue by jsmcfadyen** [Vengence99/Leatherbound-Tracker#1]
If you refactor your check_articles function to return a string instead of printing to the terminal directly, You'd be able to easily use this code to send it as an email message, or a twitter account, or anything that's not a terminal.

You'd have to change it to be print(check_articles(url)) in your main loop however.

If you get it to post to twitter, you can also mess around with hosting it in the cloud, so you don't have to run it all the time on your machine.

**Comment by Vengence99** [comment]
Issue has been resolved. Can be used for bots now.
